"""dd cascade 'all,delete'

Revision ID: 134e5a173aae
Revises: 3a1c08540958
Create Date: 2025-01-05 15:50:37.829247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134e5a173aae'
down_revision: Union[str, None] = '3a1c08540958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
