"""dd cascade 'all,delete'

Revision ID: 1ca1b4cfb556
Revises: 134e5a173aae
Create Date: 2025-01-06 21:45:48.615158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca1b4cfb556'
down_revision: Union[str, None] = '134e5a173aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_slug', table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_slug', 'tasks', ['slug'], unique=1)
    # ### end Alembic commands ###
